// Code generated by "stringer -type DataType"; DO NOT EDIT.

package main

import "strconv"

const _DataType_name = "TypUnknownTypBuiltinTypBoolTypFuncTypNumberTypString"

var _DataType_index = [...]uint8{0, 10, 20, 27, 34, 43, 52}

func (i DataType) String() string {
	if i >= DataType(len(_DataType_index)-1) {
		return "DataType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataType_name[_DataType_index[i]:_DataType_index[i+1]]
}
