// Code generated by "stringer -type Token"; DO NOT EDIT.

package main

import "strconv"

const _Token_name = "TkUnknownTkEofaddopStartTkAddTkSubtractaddopEndmulopStartTkMultiplyTkDivideTkModulomulopEndcmpopStartTkEqualTkNotEqualTkGreaterTkGreaterEqTkLessTkLessEqcmpopEndlogopStartTkAndTkOrTkNotlogopEndstmtkwdStartTkIfTkFuncTkReturnTkWhilestmtkwdEndlitStartTkBoolTkIdentifierTkNumberTkStringlitEndTkAssignTkLBraceTkRBraceTkColonTkCommaTkCommentTkElseTkLParenTkRParentendTokens"

var _Token_index = [...]uint16{0, 9, 14, 24, 29, 39, 47, 57, 67, 75, 83, 91, 101, 108, 118, 127, 138, 144, 152, 160, 170, 175, 179, 184, 192, 204, 208, 214, 222, 229, 239, 247, 253, 265, 273, 281, 287, 295, 303, 311, 318, 325, 334, 340, 348, 357, 366}

func (i Token) String() string {
	if i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
